### ISSUE TITLE
Sokal Michener definition

### ISSUE THREAD

**Issue by forgetso** [tca19/near-lossless-binarization#10]
Hi, is there a reason why your Sokal Michener function differs from other sources online? For example, Scipy sokalmichener returns a different value from your function.

```
def sokalmichener(u, v):
    ntt = np.dot(u , v.T)
    ntf = np.dot(u, 1 - v.T)
    nff = (np.dot((1.0 - u) , (1.0 - v.T)))
    nft = (np.dot((1.0 - u) , v.T))
    print(ntt + ntf + nff + nft)
    return (ntt + nff) / (ntt + ntf + nff + nft)

u=np.array([1,1,1,1,1,0,0,1])
v=np.array([1,0,0,1,1,0,0,1])
sokalmichener(u, v)
```
Returns

> 8.0
> 0.75
> 

Scipy's version:

```
distance.sokalmichener(u, v)
0.4
```

Is the Sokal Michener **dissimilarity** function a different thing?

**Comment by tca19** [comment]
Hello @forgetso ,

My implementation differs because mine is correct. According to [1] (a survey on almost all binary similiarity measures), the Sokal-Michener similarity is defined as the number of same bits divided by the total number of bits. Which is what my code does.

About the code of the function `sokalmichener()` you have written in your comment (where does it come from ? I don't think it comes from my code as there is no Python code in this repository), it is correct because it returns the number of similar bits (`ntt` + `nff`) divided by the number of all bits (if the vectors have `n` bits, then `ntt + ntf + nff + nft = n`).
But if you wanted to recreate the Scipy implementation, it is wrong:
* First, Scipy uses `R` and `S` (see [2]), where `R = 2 * (ntf + nft)` and `S = nff + ntt` (there is a coeffecient 2 for `nft` and `ntf`). The Scipy version is obviously wrong in my opininion, as it implements `1 - S_Roger&Tanimoto` where `S_Roger&Tanimoto` is defined in [1].
* Second, the fonction `sokalmichener()` implemented in Scipy is a **distance**, not a similarity. If you want a similiarity, you should use `1 - distance.sokalmichener(u, v)`.

[1] http://www.iiisci.org/journal/CV$/sci/pdfs/GS315JG.pdf
[2] https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.sokalmichener.html

**Comment by forgetso** [comment]
The code in the comment was written by me. I based it on the definition in your paper - so I'm glad to hear the Scipy version is either wrong or a different thing!

Anyway, thank you for more research that is helping me out. I'm using pre-trained models that are too big to fit on my GPU but your binarization script allows me to use them.
