### ISSUE TITLE
Potential error in read_word function

### ISSUE THREAD

**Issue by fraktlz** [tca19/near-lossless-binarization#6]
Hi,
I find your work interesting and I was reading your source code in binarize.c file. In this process, i found a potential error in read_word function.

1. `int getc_unlocked(FILE *);`
UTF8 embedding file is mainstream, Restricting the MAXWORDLEN=256 is too small while reading byte by byte, i tried some embedding file like fasttext skip-gram model and got segment fault, At first, i was confused because the max word len is 228 in  my embedding file, when i thought about its utf8 format, i understood.  i changed the MAXWORDLEN=1024 and successfully got  the result. During the process, I referenced liaocs2008's issue.
If we do not explore the max length of the vector file, we could got duplicated word because truncated by the limited MAXWORDLEN.

2. `/* skip white spaces (space or line feed (ascii code 0x0a is \n)) */
	while (isspace((tmp[i] = getc_unlocked(fp))))`
Yes, when i binarized fasttext skip-gram model using this repository,  i got error, it is just because the file contains space word like \t,space .etc. especially when i used pre-trained vector file. In current function, it just skip word and got same empty word

**Comment by tca19** [comment]
Hi,

1\. `getc_unlocked()` does not care if the file is UTF-8 or not. It reads one byte at a time, so if a file contains words encoded in UTF-16 (each character is encoded on 16 bits), it will read the word bytes by bytes until it finds a space character and store them in memory without doing any modifications. It does not matter if each character is encoded with one or two bytes.

1\. I do not agree that having `MAXWORDLEN = 256` is too small. In the worst case (with UTF-32 characters, 4 bytes per character) it represents a word with a length of 64 characters which is more than enough. I have never seen examples of words longer than 64 characters that are absolutely required in an NLP task. Moreover, some word embedding files contain garbage words. In `glove.42B.300d.txt` one can find at the line 426358 the word: 12345678910111213[...]83693 which is the contatenation of "one", "two", "three", "four"... until 368. Its length is 1000 characters, so it will be truncated but I don't think it is a significant information loss to modify the value of `MAXWORDLEN` to handle this very special case.

2. >  it is just because the file contains space word like \t,space 

I have no idea of what a space word is. By definition, a space or a `<TAB>` (\t) is not a word. So if the program finds a line that starts with whitespaces, it is the correct behaviour to keep reading characters until it finds a valid one (like a letter or a digit).
I was able to binarize fasttext English vectors (both `wiki-news-300d-1M.vec` and `crawl-300d-2M.vec`) without any troubles (after the problem here https://github.com/tca19/near-lossless-binarization/issues/5#issuecomment-549114242 was fixed) so this line is definitively not faulty.
