### ISSUE TITLE
binarize.c:(.text+0xe1c): undefined reference to `cblas_sgemm'

### ISSUE THREAD

**Issue by EmanueleLM** [tca19/near-lossless-binarization#7]
On Fedora 30, GCC 9.2.1,  I had to add to the makefile at line 23 the lib '-lcblas' to proper run make.
From:
```LDLIBS  = -lblas -lm```
to:
```LDLIBS  = -lblas -lm -lcblas```

**Comment by tca19** [comment]
Hello @EmanueleLM ,

On Debian sid with GCC 9.3.0, adding `-lcblas` to the variable `LDLIBS` in makefile produce the following error:

`/usr/bin/ld: cannot find -lcblas`

And the executables are not created . For this reason, I cannot accept your suggestion to the current makefile. I think the problem comes from the installation of OpenBLAS. How did you install the OpenBLAS library on your Fedora system? Have you followed the commands explained at https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages#fedoracentosrhel ? Can you check if the `libblas` files are present in your lib folder (in my case, I can see `libblas.a` and `libblas.so` in the output of the command `ls /usr/lib/x86_64-linux-gnu/ | grep -i blas`, but it might be in another folder on Fedora).

**Comment by tca19** [comment]
Closing this issue (no answers from the author of the issue).
