### ISSUE TITLE
Small Embeddings

### ISSUE THREAD

**Issue by EmanueleLM** [tca19/near-lossless-binarization#8]
When I execute this code with embeddings of small size (e.g., GloVeTwitter 25d) I'd like to use a representation that is smaller than 64 bits, but it doesn't work as the output file doesn't support anything that is smaller than that size.

Is there a way to obtain smaller, binary embeddings with this method?

Thank you,
Emanuele

**Comment by tca19** [comment]
Hello @EmanueleLM ,

The output file is created by the function `write_binary_vectors()` in `binarize.c`. See https://github.com/tca19/near-lossless-binarization/blob/dd5f43245720a5c691feca2b1efed28856535bb1/binarize.c#L403 Binary vectors are saved as groups of 64 bits using a `long` integer (on common machines, a `long` has 64 bits). I think that you can learn binary vectors of 32 bits by changing `long` to `int` (which use 32 bits) in the function `binarize()` at line 328. https://github.com/tca19/near-lossless-binarization/blob/dd5f43245720a5c691feca2b1efed28856535bb1/binarize.c#L328 But this would imply to also modify the functions that update the binary embeddings, as they have been created to operate on `long` integers, not `int` integers. So obtaining smaller binary embeddings of 32 bits can be done but it requires some modifications in the source code.

If your objective is to create (and learn) binary embeddings of smaller size (for example, 25 bits), I think it will be more complicated. Indeed, the binary vectors are represented in memory with integers, and the size of integers in computers is a power of 2 (most common ones are 16 bits, 32 bits and 64 bits). So you cannot create binary embeddings of 25 bits in a straightforward way. Moreover, even if you create a specific data structure that has only 25 bits, binary vector operations like XOR are still done with 32 or 64 bits in processors (the processor might add a zero-padding in that case). A possible solution would be to train the binary embeddings with 32 or 64 bits, but when saving them, only write the first 25 bits into the file. In that case, only the function `write_binary_vectors()` would need to be modified (rest of the code does not change because the learning method has not changed). The disadvantage of this is that the model has been trained to use all the 32 or 64 bits for reconstruction, so the information loss would be important if only the 25 first bits are kept.
